version: '3.9'
services:
  postgres:
    container_name: rood_postgres
    image: postgres:14.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    logging:
      driver: "local"
  strapi:
    container_name: rood_strapi
    build: ./roodjongeren/backend
    restart: unless-stopped
    environment:
      - URL=$STRAPI_URL
      - HOST=$STRAPI_HOST
      - PORT=$STRAPI_PORT
      - ADMIN_JWT_SECRET=$STRAPI_ADMIN_JWT_SECRET
      - JWT_SECRET=$STRAPI_JWT_SECRET
      - API_TOKEN_SALT=$STRAPI_API_TOKEN_SALT
      - APP_KEYS=$STRAPI_APP_KEYS
      - SMTP_HOST=$STRAPI_SMTP_HOST
      - SMTP_PORT=$STRAPI_SMTP_PORT
      - SMTP_USERNAME=$STRAPI_SMTP_USERNAME
      - SMTP_PASSWORD=$STRAPI_SMTP_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - STRAPI_LICENSE=$STRAPI_LICENSE
    depends_on:
      - postgres
    volumes:
      - strapi_uploads_volume:/usr/src/app/public/uploads
    logging:
      driver: "local"
    ports:
      - "1337:1337"
  nextjs:
    container_name: rood_nextjs
    build: ./roodjongeren/frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=$STRAPI_URL
      - NEXT_PUBLIC_BACKEND_URL=/backend
    depends_on:
      - strapi
    logging:
      driver: "local"
    ports:
      - "3000:3000"
  umami_postgres:
    container_name: umami_postgres
    image: postgres:14.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$UMAMI_DATABASE_USER
      - POSTGRES_PASSWORD=$UMAMI_DATABASE_PASSWORD
      - POSTGRES_DB=$UMAMI_DATABASE_NAME
    volumes:
      - umami_postgres_volume:/var/lib/postgresql/data
    logging:
      driver: "local"
  umami:
    container_name: umami
    build:
      context: ./roodjongeren/docker/umami
      args:
        - BASE_PATH=/umami
        - DATABASE_TYPE=postgresql
    restart: unless-stopped
    depends_on:
      - umami_postgres
    environment:
      - DATABASE_URL=postgresql://${UMAMI_DATABASE_USER}:${UMAMI_DATABASE_PASSWORD}@umami_postgres:5432/${UMAMI_DATABASE_NAME}
      - BASE_PATH=/umami
      # Allows us to change the name of the generated JS file
      # A custom name reduces the chance of ad blockers preventing our analytics from working
      - TRACKER_SCRIPT_NAME=stasi
      - COLLECT_API_ENDPOINT=/stasi/knock
    ports:
      - '3100:3000'
    logging:
      driver: "local"
volumes:
  postgres_volume:
    name: rood_postgres_volume
    driver: local
  strapi_uploads_volume:
    name: rood_strapi_volume
    driver: local
  umami_postgres_volume:
    name: umami_postgres_volume
    driver: local
